{% set name = "modelx-cython" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelx-cython-{{ version }}.tar.gz
  sha256: f016c441a26a741734ac53b3a642b819260f4160686f6a8567aeadb13a8d520a

build:
  skip: true  # [py<37]
  entry_points:
    - mx2cy = modelx_cython.cli:entry_point_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - modelx
    - libcst
    - cython
    - setuptools
    - monkeytype
    - numpy

test:
  imports:
    - modelx_cython
  commands:
    - pip check
    - mx2cy --help
  requires:
    - pip

about:
  home: https://github.com/fumitoh/modelx-cython
  summary: Cythonize modelx models.
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
