{% set name = "modelx-cython" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 643e5e01c934d3e22cd79e0ceac5f1bdbc06f6f68c4fe172677be4b4851b3a98

build:
  skip: true  # [py<37]
  entry_points:
    - mx2cy = modelx_cython.cli:entry_point_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - modelx
    - libcst
    - cython
    - setuptools
    - monkeytype
    - numpy

test:
  imports:
    - modelx_cython
  commands:
    - pip check
    - mx2cy --help
  requires:
    - pip

about:
  home: https://github.com/fumitoh/modelx-cython
  summary: Cythonize modelx models.
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
